version: '3'
services:

  quizgame-database:
    build: ./database
    env_file:
      - ./.env
    ports:
      - 5432:5432
    user: postgres
    healthcheck:
      test: pg_isready
      start_period: 5s
      interval: 2s
      retries: 15

  quizgame-backend:
    build: ./backend
    env_file:
      - ./.env
    ports:
      - 8080:8080
    depends_on:
      quizgame-database:
        condition: service_healthy
    healthcheck:
      test: curl --fail --request GET http://localhost:8080/actuator/health
      start_period: 10s
      interval: 2s
      retries: 15
  
  quizgame-initialization:
    build: ./initialization
    command:
      run /usr/app/initialization.json
      --env-var "URL=http://quizgame-backend:8080"
      -r cli,json
      --reporter-json-export="reports/initialization-report.json"
    depends_on:
      quizgame-backend:
        condition: service_healthy
    healthcheck:
      test: bash -c "[ -f /reports/initialization-report.json ]"
      start_period: 5s
      interval: 2s
      retries: 15
    profiles:
      - init

  quizgame-frontend:
    build: ./frontend
    ports:
      - 4200:4200
